name: Build and Scan

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Image
        run: docker build -t app:test .

      - name: Run Trivy Scan (Safe Mode)
        run: |
          docker run --rm aquasec/trivy image app:test || true